pipeline{
    parameters{
        choice(name: 'terraformAction',choices: ['apply','destroy'],description: 'Choose your Terraform action')
    }

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    agent any

    stages{
        stage('Checkout'){
            steps{
                script{
                    dir("terraform"){
                        git url: 'https://github.com/lmanoj0620/Chatbbot.git',branch: 'main'
                    }
                }
            }
        }

        stage('Plan'){
            steps{
                sh 'pwd; cd IAC/; terraform init'
                sh 'pwd; cd IAC/; terraform plan -out tfplan'
                sh 'pwd; cd IAC/; terraform show -no-color tfplan > tfplan.txt'
            }
        }

        stage('Approval'){
            steps{
                script{
                    def plan = readFile 'IAC/tfplan.txt'
                    input message: "Do you want to proceed with the Terraform action?",
                    parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                }
            }
        }

        stage('Apply or Destroy'){
            when {
                expression{
                    return  params.terraformAction == 'apply' || params.terraformAction == 'destroy'
                } 
            }
            steps{
                script{
                    if (params.terraformAction == 'apply'){
                        sh 'pwd; cd IAC/; terraform apply -input=false tfplan'
                    }
                    else if (params.terraformAction == 'destroy'){
                        sh 'pwd; cd IAC/; terraform destroy -auto-approve'
                    }
                }
            }
        }
        stage("Backup to store statefile"){
            steps{
                sh """ 
                    pwd
                    cd IAC/
                    aws s3 cp terraform.tfstate s3://demo-bucket-489393/chatbot/IAC/
                """
        }
    }
        
    }     

}
